return {
  { import = 'plugins.dap' },
  { import = 'plugins.dap.lang' },
  { import = 'plugins.explorers' },
  { import = 'plugins.fun' },
  { import = 'plugins.git' },
  { import = 'plugins.lang' },
  { import = 'plugins.lang.html' },
  { import = 'plugins.lang.lua' },
  { import = 'plugins.lang.markdown' },
  { import = 'plugins.lsp' },
  { import = 'plugins.sessions' },
  { import = 'plugins.signs' },
  { import = 'plugins.snippets' },
}
